version: '3.2'
services:

  helloworld-db-postgres:
    image: "registry.k8.wildwidewest.xyz/repository/docker-repository/helloworld-db:${tag}"
    build: .

  helloworld-db:
    image: "registry.k8.wildwidewest.xyz/repository/docker-repository/helloworld-db:${tag}"
    build: .
